# Use the .NET 8 SDK to build the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Copy the build files
COPY ./bin/Release/net8.0/publish/ .

# Start the app
ENTRYPOINT ["dotnet", "AppieName.dll"]