name: .NET docker CI/CD Pipeline

on:
  workflow_dispatch: # 👈 This enables manual "Run workflow" trigger from Actions tab
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "v8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Build Docker image
        run: docker build -t my-dotnet-app ./publish

      - name: Run Docker container
        run: |
          docker stop my-running-app || true
          docker rm my-running-app || true
          docker run -d --name my-running-app -p 80:80 my-dotnet-app
