name: .NET CI/CD Pipeline

on:
  push:
    branches: [ master ]  # Change if your main branch is called 'main'

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted

    env:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore $env:solution

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build the solution
      run: msbuild $env:solution /p:Configuration=$env:buildConfiguration /p:Platform="$env:buildPlatform" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}\\drop\\WebApp.zip" /p:DeployIisAppPath="Default Web Site"

    - name: Run Tests
      uses: microsoft/vstest-action@v1
      with:
        platform: ${{ env.buildPlatform }}
        configuration: ${{ env.buildConfiguration }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: drop/WebApp.zip

  deploy:
    name: Deploy to Azure Web App
    needs: build
    runs-on: windows-2022

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: drop

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devWebapp101'
        slot-name: 'production'
        package: drop/WebApp.zip
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
