name: .NET CI/CD Pipeline

on:
  workflow_dispatch:  # 👈 This enables manual "Run workflow" trigger from Actions tab

jobs:
  build:
    name: Build and Test
    runs-on: windows-2022
    permissions:
      contents: read
#on:
#  push:
#    branches: [ master ]  # Change if your main branch is called 'main'

#jobs:
#  build:
#    name: Build and Test
#    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: 'v8.0'
         
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests (if any)
      run: dotnet test --no-build --verbosity normal

    - name: Publish to temp folder
      run: dotnet publish -c Release -o ./publish_output --no-build  # Publish compiled app to ./publish_output

    - name: Upload published artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dotnet8-app-publish
        path: ./publish_output

  deploy:
    name: Deploy to Azure Web App
    needs: build
    runs-on: windows-2022

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gitappPIP'
        slot-name: 'production'
        package: ./publish_output
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
